### ISSUE TITLE
choice.com for 64bits Windows 10

### ISSUE THREAD

**Issue by bernique** [ScriptTiger/Unified-Hosts-AutoUpdate#4]
Hi
When I run the .cmd on my Windows 10 64bits, I get a lot of errors with system32/choice.com not being suitable on 64b systems. It should work with /system32/choice.exe. How to solve this?
Thanks
LT

**Comment by ScriptTiger** [comment]
Hmm... To be honest I wrote the script on my Windows 10 64-bit machine, so I will have to do some more research and get back to you on this. In the meantime, you should still be able to manually make a scheduled task and run automatic updates because automatic updates bypass choice.

**Comment by ScriptTiger** [comment]
Is there something else different about your OS? I think your system directory has been altered, because choice is not a .com, it is an .exe. Can you check your system32 directory and see if you have a choice.exe and .com? If you have both, save the .com somewhere for backup, and then try deleting it from your system directory.

It would probably be a good idea to also do a virus scan for malware and rootkits, also, just to be safe, unless you know why your system is different.

**Comment by bernique** [comment]
Thanks for your prompt reply. I can see the choice.exe in my system32 folder, but I get the following errors (my OS is French):
![image](https://user-images.githubusercontent.com/9451214/29583326-044e67e6-8780-11e7-853d-d32ccb38262e.png)
It clearly refers to /system32/choice.com, which does not exits.
Any idea?

**Comment by ScriptTiger** [comment]
Did you mean to close this? I have some ideas of how to fix this if this is still an issue.

**Comment by ScriptTiger** [comment]
I also am not sure why it has "\??\" in the path. Press Windows key+R, type "cmd" and enter, and then type these commands one by one and take a screenshot or copy and paste the results here:

echo %path%
echo %pathext%
echo %systemroot%
choice
choice.exe
choice.com

If it says "[Y,N]?", just press Y and continue.

Also, try replacing your Update_Hosts.cmd with the one inside this ZIP file and tell me what happens.

**Comment by bernique** [comment]
Here are the results:
C:\WINDOWS\system32>echo %path%
C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Skype\Phone;C:\ProgramData\chocolatey\bin;;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Users\loic\AppData\Local\Microsoft\WindowsApps;C:\Program Files\WTServer\bin

C:\WINDOWS\system32>echo %pathext%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

C:\WINDOWS\system32>echo %systemroot%
C:\WINDOWS

C:\WINDOWS\system32>choice
[O,N]?N

C:\WINDOWS\system32>choice.exe
[O,N]?N

C:\WINDOWS\system32>choice.com
'choice.com' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

**Comment by ScriptTiger** [comment]
Have you also tried to replace the script with the one in the ZIP file?

**Comment by bernique** [comment]
Done. I still have the same error, except for the 2 first lines:
![image](https://user-images.githubusercontent.com/9451214/29599743-14ffdb0e-87d2-11e7-9104-73efdc686ae2.png)
which say that the script is up to date and that I have a scheduled task. This is new.

**Comment by bernique** [comment]
What is the name and location of your task?

**Comment by ScriptTiger** [comment]
You can view the task by opening your Task Scheduler:
Windows key+R, "taskschd.msc"
And look for "Unified Hosts AutoUpdate"
Or you can view it in the command line:
Windows key+R, "cmd", and type this:
schtasks | findstr "Unified Hosts AutoUpdate"

If the script is not working correctly on your machine, it may say you have a scheduled task even if you really don't.

I can see in your screenshot you are using the SysWOW64\cmd.exe. The script should work fine with it, but the default is the system32\cmd.exe, even on a 64-bit machine. How are you executing the script? Are you opening the the SysWOW64\cmd.exe first with admin rights and then running the script inside the command prompt? Or are you just right-clicking the script and running with admin rights? Like I said, it should still work fine, but I am just curious to what extent your defaults are different.

And here is another script for you to test.

I am sorry to ask you for so many things, but I just like to be as complete as possible. I hope you do not feel rushed and please take your time. And thank you very much for your interest and feedback!

**Comment by bernique** [comment]
To get cmd, I use the right-click on the Start icon.
Your last script works fine!
![screen 20170823-082007](https://user-images.githubusercontent.com/9451214/29601543-66ebc1f8-87dc-11e7-8616-172374eba52c.png)
But I can't get your task:
C:\WINDOWS\system32>schtasks | findstr "Unified Hosts AutoUpdate"
TrackerAutoUpdate                        03/09/2017 09:00:00    Prêt
I'm like you, I like to fully understand issues, you don't bother me. Thanks for your work.

**Comment by bernique** [comment]
I have restarted cmd several times, and I am on system32 each time. I don't know how I got to SysWOW64\cmd.exe but I cannot reproduce.

**Comment by ScriptTiger** [comment]
Oh, I'm sorry, you must run cmd as administrator to view the task because it runs as the system. Try this:
Windows Key+R, "C:\WINDOWS\System32", enter.
Then find the cmd.exe and right-click it and run with admin rights. Then type the command I gave you before:
schtasks | findstr "Unified Hosts AutoUpdate"

It should show you this time, sorry about that.

Can you also try one more script for me? I would like to update the script for everyone so others don't have the same problem in the future, but I want to make sure I understand the problem correctly first.

Thank you so much, again!

**Comment by bernique** [comment]
I run command as administrator, right-click on Windows Start icon allows that directly. Whichever the way I open cmd as administrator, I get the same result.
I test your last script.

**Comment by ScriptTiger** [comment]
I just pushed an update to resolve the choice problem and scheduled task problem you were having. The next time you run your script, it should update itself and run correctly.

The scheduled task was not working on your machine because you have another scheduled task with a similar name and it was confusing my script. So I just made my script look more specifically so it should not have that problem in the future.

**Comment by bernique** [comment]
The script seems to work, but with all my trials, I still have a problem with the scheduled task. I have tried to remove it, but I get this error:
C:\Users\loic\Documents\Informatique\Install\Unified-Hosts-AutoUpdate-master>Hosts_Update.cmd
Checking for script updates...
Your script is up to date
You currently have a scheduled task already in place
Would you like to keep it? [O,N]?N
Erreur : Le fichier spécifié est introuvable.
It seems that the task is recorded somewhere, but does not really exists. Any idea?

**Comment by ScriptTiger** [comment]
Sorry, I think I replied too fast. Please read my comment above.

> I just pushed an update to resolve the choice problem and scheduled task problem you were having. The next time you run your script, it should update itself and run correctly.
>
>The scheduled task was not working on your machine because you have another scheduled task with a similar name and it was confusing my script. So I just made my script look more specifically so it should not have that problem in the future.

**Comment by bernique** [comment]
Everything seems to work perfectly with your last script. Thanks a lot!

**Comment by ScriptTiger** [comment]
And thank you for being so patient!

**Comment by LANCENET** [comment]
Add token
