### ISSUE TITLE
Always retry downloads

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#43]
It looks like some downloads are retried and some aren't. I keep failing on "connectivity issues" but there is nothing wrong with my internet, I'm guessing these are the culprits (but I can't be sure since the error message doesn't specify the URL it was trying to download):

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/8730f69ad6eb1ed70a6d31d4b853dffd9268557a/Hosts_Update.cmd#L115

https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/8730f69ad6eb1ed70a6d31d4b853dffd9268557a/Hosts_Update.cmd#L286

I think the logical thing to do would be to replace them with `Download` calls (more consistent too):
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/8730f69ad6eb1ed70a6d31d4b853dffd9268557a/Hosts_Update.cmd#L684

**Comment by ScriptTiger** [comment]
Due to the way permissions around BITS work, the script requires two connectivity checks that bypass the `:Download` function. Some people do have an Internet connection, but just don't have permission to access BITS directly, as "Run as administrator" has certain restrictions and is not the same as running from an account that is actually a member of the local administrators group. In these cases the script runs in a special mode to set up the scheduled task and run the scheduled task, as the scheduled task has the appropriate permissions to run even though the user does not.

The reason why there are two checks is because some users choose to bypass the first check by not allowing script updates. In these cases, a second check is required. After both checks are conducted, the script then makes an assumption about the connection and proceeds from there, using the `:Download` function throughout the rest of the script.

What I can do here is add another check, just a simple ping, to directly test the connection separate from just whether or not BITS works. Then the script can determine the difference whether the Internet connection is actually dead or if it's actually just a BITS permission problem, as right now it does not distinguish. Either way, if in interactive offline mode, it can proceed to carry out the rest of the script as usual using the programming already there to work with BITS permissions. If the script is not in interactive offline mode, it will simply exit and display the error message.

That work?

**Comment by ScriptTiger** [comment]
Added a cap of 3 retries, with incremental time delays of an additional 30 seconds each additional retry.

Please manually update and let me know your feedback before I push this as a release.

**Comment by ScriptTiger** [comment]
Also, please check out the new error code table in the new readme, as I have made some changes to reflect system connectivity issues versus BITS connectivity issues to better distinguish the issue when debugging. Upon encountering such errors, I also have it state the URL it is having a problem with, as well.

**Comment by ohadschn** [comment]
> Due to the way permissions around BITS work, the script requires two connectivity checks that bypass the `:Download` function. Some people do have an Internet connection, but just don't have permission to access BITS directly, as "Run as administrator" has certain restrictions and is not the same as running from an account that is actually a member of the local administrators group. In these cases the script runs in a special mode to set up the scheduled task and run the scheduled task, as the scheduled task has the appropriate permissions to run even though the user does not.
> 
> The reason why there are two checks is because some users choose to bypass the first check by not allowing script updates. In these cases, a second check is required. After both checks are conducted, the script then makes an assumption about the connection and proceeds from there, using the `:Download` function throughout the rest of the script.

So these checks make sense in interactive mode, but since you're failing the script in quiet mode anyway, I would say in quiet mode just always use `:Download`. That way you are resilient to intermittent network failures even in your those checks.

> What I can do here is add another check, just a simple ping, to directly test the connection separate from just whether or not BITS works. Then the script can determine the difference whether the Internet connection is actually dead or if it's actually just a BITS permission problem, as right now it does not distinguish. Either way, if in interactive offline mode, it can proceed to carry out the rest of the script as usual using the programming already there to work with BITS permissions. If the script is not in interactive offline mode, it will simply exit and display the error message.
> 
> That work?

Yes, but only in interactive (non-quiet) mode.

>  I also have it state the URL it is having a problem with, as well.

Works great!

**Comment by ScriptTiger** [comment]
Fixed this, check it again and let me know.

**Comment by ohadschn** [comment]
`:Download` usage looks good!

Still not crazy about the `ping` though:
1. Also redundant in quiet mode, and it's not clear how resilient it is to intermittent network failures (specifically in terms of retries).
1. It's not clear (and [not documented](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping)) when exactly `ping` return non-zero status codes. Specifically, there could be [failures that still result in ERRORLEVEL 0](https://superuser.com/questions/403905/ping-from-windows-7-get-no-reply-but-sets-errorlevel-to-0). According to that thread, `-n -w` is the best practice to avoid that issue.
1. GitHub may block ping requests on its domain at any time (like `microsoft.com` does), I think a better practice would be specifying an explicit IP that will never change, say Google's 8.8.8.8.

**Comment by ScriptTiger** [comment]
> Also redundant in quiet mode, and it's not clear how resilient it is to intermittent network failures (specifically in terms of retries).

I don't really agree here. If you don't have a connection, the initial ping check will cut the script without going any further. Yes, the script could just skip it and waste time going through the whole exponential delay sequence, etc., etc., and ultimately throw a failed download error. However, this will just end it without wasting any further time or resources and give you a more specific error that tells you it's specifically the connection and not an error specifically causing a failed download, like maybe your connection is too unstable or is taking too long and causing the server to time out on the download even though it does have a connection.

> It's not clear (and not documented) when exactly ping return non-zero status codes. Specifically, there could be failures that still result in ERRORLEVEL 0. According to that thread, -n -w is the best practice to avoid that issue.

I just implemented `ping -n 10 -w 2000`,  check it out and let me know.

> GitHub may block ping requests on its domain at any time (like microsoft.com does), I think a better practice would be specifying an explicit IP that will never change, say Google's 8.8.8.8.

I'll address this if/when this actually becomes a problem. My script also requires DNS to resolve `raw.githubusercontent.com` in the first place, so it's better if it's a domain name and not an IP address. And it's even better still if it's the one and only domain name the script actually requires to work. And in some countries, believe it or not, 8.8.8.8 is actually blocked, especially in some countries with censorship that block known DNS/DoT/DoH providers. So I am not going to presume any specific IP address, other than the one needed to resolve to by the `raw.githubusercontent.com` domain.

**Comment by ohadschn** [comment]
> I don't really agree here. If you don't have a connection, the initial ping check will cut the script without going any further

The point is, you have no way of discerning between "no connection" and "intermittent issue". So going through the exponential retry delay sequence might actually make the script work rather than fail. At least in quiet mode it can't hurt, nobody cares if something took 1 minute or 10 minutes for some unattended job in the middle of the night.

> I just implemented ping -n 10 -w 2000, check it out and let me know.

Looks good! I'm still not sure about exactly when `ping` returns non-zero return codes, but I opened an issue to try and figure it out: https://github.com/MicrosoftDocs/windowsserverdocs/issues/3797

> I'll address this if/when this actually becomes a problem. My script also requires DNS to resolve raw.githubusercontent.com in the first place, so it's better if it's a domain name and not an IP address. And it's even better still if it's the one and only domain name the script actually requires to work. And in some countries, believe it or not, 8.8.8.8 is actually blocked, especially in some countries with censorship that block known DNS/DoT/DoH providers. So I am not going to presume any specific IP address, other than the one needed to resolve to by the raw.githubusercontent.com domain.

If you want to test DNS resolution, a better bet might be something like `nslookup` ([though it seems to return 0 regardless, so output parsing might be necessary](https://stackoverflow.com/questions/41060027/how-to-use-nslookup-in-bash-to-verify-is-dns-is-configured-properly)). `ping` confounds DNS resolution with blocking of the ping protocol itself.

**Comment by ScriptTiger** [comment]
> The point is, you have no way of discerning between "no connection" and "intermittent issue". So going through the exponential retry delay sequence might actually make the script work rather than fail. At least in quiet mode it can't hurt, nobody cares if something took 1 minute or 10 minutes for some unattended job in the middle of the night.

Hmm... Well, I suppose it won't hurt in this case. I just suppressed pinging in quiet mode, check it out.

I should probably give you a backstory as to why I am so paranoid and bent on cutting scripts as early as possible, just so you don't think I am more crazy than you already do and better understand why I have a best practice to follow that principle. Microsoft has been making random updates in recent times to the way it "optimizes performance" of background and foreground processes. Some scripts that iterate a lot actually start to drain memory that cannot be recovered without actually restarting the system. I don't know if Microsoft is actively working to improve these features or not, but for the time being some scripts that iterate a lot can only be run in safe mode without all those optimization services running.

> If you want to test DNS resolution, a better bet might be something like nslookup (though it seems to return 0 regardless, so output parsing might be necessary). ping confounds DNS resolution with blocking of the ping protocol itself.

I can't use `nslookup` because it will not work with people using multiple network adapters and advanced IPv4 and IPv6 configurations at the same time. People running such setups would require additional parameters and knowledge of their network configuration just to make `nslookup` function. Otherwise, if such specific parameters are not given, `nslookup` will try to find the appropriate information on its own and possibly grab the wrong information from the wrong adapter or protocol and just get `*** UnKnown can't find google.com: Query refused`.

And on top of all of that, in this day and age I would hope a company like GitHub, now owned by Microsoft, made the conscious decision to allow ICMP in the first place and isn't just doing it accidentally. Many larger enterprises even redirect ICMP traffic to special servers designed just to handle that traffic, since obviously DoD and DDoS are all the rage these days. So the way I see it is I am just using another service they are consciously providing me. If they should decide to stop providing that service in the future, as I said, I'll adapt as that happens.

**Comment by ScriptTiger** [comment]
> Looks good! I'm still not sure about exactly when ping returns non-zero return codes, but I opened an issue to try and figure it out: MicrosoftDocs/windowsserverdocs#3797

I'll also note to this point that we also don't have to confine ourselves to simply the returned exit code of ping. If need be, the ping output could be more deeply analyzed directly, like how `Ping_Test.cmd` breaks down ping results in my IP repo (https://github.com/ScriptTiger/IP) to build statistics. Although I don't see an imminent need for this at the moment, there are no limitations here as to the desired conditions to constitute and error. We could base the error conditions on everything from packet loss percent to actual number of packets sent and/or received, etc.

**Comment by ScriptTiger** [comment]
I'm closing this issue just because the actual topic issue was resolved, but I think we will probably revisit the ping topic separately later on.
